import React from "react";
import type { Metadata } from "next";
import {montserrat, openSans} from "@/utils";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cater Ease",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${openSans.variable} font-primary antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
