import React from "react";
import type {Metadata} from "next";
import {montserrat, openSans} from "@/utils";
import "./globals.css";
import {ThemeProvider} from "@/components/theme/theme-provider";
import {Toaster} from "react-hot-toast";


export const metadata: Metadata = {
    title: "Cater Ease",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${montserrat.variable} ${openSans.variable} font-primary antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            {children}
            <Toaster
                position="top-center"
                toastOptions={{
                    className: 'text-sm dark:bg-black dark:text-white shadow-md rounded-lg',
                }}
            ></Toaster>
        </ThemeProvider>
        </body>
        </html>
    );
}
