import React from "react";
import type { Metadata } from "next";
import {montserrat, openSans} from "@/utils";
import "./globals.css";
import {ThemeProvider} from "@/components/theme/theme-provider";

export const metadata: Metadata = {
  title: "Cater Ease",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.variable} ${openSans.variable} font-primary antialiased`}
      >
        <main>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                {children}
            </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
